CREATE TABLE user(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
  username VARCHAR(50) NOT NULL ,
  email VARCHAR(50) NOT NULL ,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE ads(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(250),
  description TEXT,
  FOREIGN KEY (user_id) REFERENCES user(id)
);